# Generated by Django 2.2.7 on 2019-12-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_brand', models.CharField(max_length=256, verbose_name=' Name brand')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categories', models.CharField(max_length=256, verbose_name='Name categories')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectForCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_model', models.CharField(max_length=256, verbose_name=' Name model')),
                ('object_text', models.TextField(verbose_name='description')),
                ('object_price', models.CharField(max_length=256)),
                ('object_picture', models.ImageField(upload_to='')),
                ('add_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
                ('add_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Categories')),
            ],
        ),
    ]
