# Generated by Django 2.2.7 on 2019-12-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='object_brand',
            new_name='name_brand',
        ),
    ]
