# Generated by Django 2.2.7 on 2019-12-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191209_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectForCategories',
            new_name='Goods',
        ),
    ]
