# Generated by Django 3.0 on 2019-12-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191209_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name_brand',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='name_categories',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='add_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='add_categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='object_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='object_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='object_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='object_text',
            new_name='text',
        ),
    ]
